import streamlit as st
import os
import tempfile
import json
from parse_transcript import parse_transcript

# Initialize the environment and output directory
os.makedirs("output", exist_ok=True)

st.set_page_config(page_title="Transcript AI Parser", page_icon="📝")

st.title("📝 Transcript AI Parser")
st.markdown("""
This UI allows you to upload customer service transcripts for semantic processing. 
The system will:
1. **Analyze** the text using Gemini 3.6 Flash.
2. **Extract** key metadata into structured JSON.
3. **Ingest** the results directly into BigQuery.
""")

uploaded_file = st.file_uploader("Upload Transcript (.txt)", type=['txt'])

if uploaded_file:
    # Show a snippet of the transcript
    file_text = uploaded_file.read().decode("utf-8")
    st.text_area("Transcript Preview", file_text, height=200)

    if st.button("🚀 Run AI Pipeline"):
        # Use a temporary file to integrate with the existing file-based parse_transcript logic
        with tempfile.NamedTemporaryFile(delete=False, suffix=f"_{uploaded_file.name}") as tmp:
            tmp.write(file_text.encode("utf-8"))
            tmp_path = tmp.name

        try:
            with st.status("AI Extraction and BigQuery Sync...", expanded=True) as status:
                st.write("Calling Gemini AI...")
                # This executes the full logic: AI parse -> Local JSON -> BigQuery
                parse_transcript(tmp_path)
                status.update(label="Task Finished!", state="complete", expanded=False)

            # Locate the output file generated by parse_transcript.py
            base_temp_name = os.path.splitext(os.path.basename(tmp_path))[0]
            output_path = f"output/{base_temp_name}.json"

            if os.path.exists(output_path):
                with open(output_path, 'r') as f:
                    parsed_json = json.load(f)
                st.subheader("Extracted JSON Data")
                st.json(parsed_json)
                st.success("Data successfully persisted to BigQuery and local storage.")

        except Exception as e:
            st.error(f"Pipeline failed: {str(e)}")
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)